### ISSUE TITLE
admin panel plugin error

### ISSUE THREAD

**Issue by Unity4K** [Dem13n/discussion-cards#2]
i updated the plugin and again the problem persists

When you activate the plugin, the articles on the main page disappear

![wws](https://user-images.githubusercontent.com/69718465/106423906-5c265f00-6472-11eb-9427-a71edc1b3a3e.png)

**Comment by Dem13n** [comment]
try uninstalling and reinstalling, no need to update

composer remove dem13n/discussion-cards
composer require dem13n/discussion-cards

**Comment by Unity4K** [comment]
> try uninstalling and reinstalling, no need to update
> 
> composer remove dem13n/discussion-cards
> composer require dem13n/discussion-cards

I did what you said I still get the same error

**Comment by Dem13n** [comment]
in the database, in migrations, delete the line 2021_01_31_000000_set_default_settings

composer remove dem13n/discussion-cards
composer require dem13n/discussion-cards

**Comment by Unity4K** [comment]
> in the database, in migrations, delete the line 2021_01_31_000000_set_default_settings
> 
> composer remove dem13n/discussion-cards
> composer require dem13n/discussion-cards
> 
> don't forget to disable and enable the extension

the problem is fixed thanks
