### ISSUE TITLE
TypeError: t.firstPost(...).contentPlain is not a function

### ISSUE THREAD

**Issue by phenomlab** [Dem13n/discussion-cards#21]
Suddenly, I get the below in the console

```
TypeError: t.firstPost(...).contentPlain is not a function
    at s.e.view (ListItem.js:90)
    at Function.a (render.js:30)
    at render.js:155
    at render.js:160
    at l (render.js:66)
    at u (render.js:50)
    at render.js:103
    at l (render.js:62)
    at u (render.js:50)
    at render.js:134
```

No errors being recorded in log, but extension does not function and crashes the forum unless I disable it.

**Comment by phenomlab** [comment]
Just tried the new release - still the same error above, but only if you set less than 10 primary cards.

**Comment by phenomlab** [comment]
I actually do not want to have primary cards if possible.

**Comment by Dem13n** [comment]
does the error persist with version 0.3.5 ?

**Comment by phenomlab** [comment]
No. Works as expected - I have set to 0. Thanks !
