### ISSUE TITLE
Compatibility with synopsis

### ISSUE THREAD

**Issue by T0MMYRR** [Dem13n/discussion-cards#3]
My congratulations for this extension is really useful and very aesthetic! 
Regarding the issue, I think it would be nice to add compatibility with the synopsis extension to add more information to the cards before entering. Thanks for this extension.

**Comment by Dem13n** [comment]
https://github.com/Dem13n/discussion-cards/commit/360a2dd3541ed5786612eff3dbe10a0b0a5bd120, I did, but without setting the number of characters, just limited the output to 3 lines and a maximum of 150 characters

**Comment by T0MMYRR** [comment]
I didn't see it until now, something happened to the Github notifications.... Thank you very much, it works really well!
