### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by legotom** [Dem13n/discussion-cards#6]
It would be nice to add mobile support, currently the interface does not support it if the cards are squashed, here is an image.

![](https://i.ibb.co/1bcxzfG/Captura-de-pantalla-2021-02-14-225353.png)

**Comment by legotom** [comment]
Oops sorry this is currently my custom css problem, I tried to put 3 cards per row (div.CardsListItem.smallCard {width: 32%;}) and broke the mobile view, is there any way to do this without that happening?

**Comment by Dem13n** [comment]
try to change the width of the forum.less, and not through the admin panel
