### ISSUE TITLE
Problem with the discussion context menu

### ISSUE THREAD

**Issue by legotom** [Dem13n/discussion-cards#7]
The menu stays inside the card and if the image is small it does not allow access to most functions. For example in this case:

![](https://i.ibb.co/x1ndxqG/Captura-de-pantalla-2021-02-14-230015.png)

**Comment by Dem13n** [comment]
fixed https://github.com/Dem13n/discussion-cards/commit/e7e0ab56e2aff5fc805201abb88552466031a158
