### ISSUE TITLE
The title area shifts to the bottom of the header section when the editor is fullscreen

### ISSUE THREAD

**Issue by ayyilmaz** [Dem13n/discussion-cards#9]
After activating the Discussion cards plugin, the title area shifts to the bottom of the header section when the editor is fullscreen.
I cannot shrink the composer window again.. I need to refresh page with f5. Logo is not clickable when it is fullscreen.

![](https://i.imgur.com/VSrVRXY.png)

**Comment by Dem13n** [comment]
fixed, and https://github.com/Dem13n/discussion-cards/discussions/8#discussion-3271937

**Comment by Dem13n** [comment]
> After activating the Discussion cards plugin, the title area shifts to the bottom of the header section when the editor is fullscreen.
> I cannot shrink the composer window again.. I need to refresh page with f5. Logo is not clickable when it is fullscreen.
> 
> ![](https://camo.githubusercontent.com/b753c42a688aca80cc582760dd6166338e7fdb4f9296c0557a682faf69876bfd/68747470733a2f2f692e696d6775722e636f6d2f565372565258592e706e67)

fixed, and added https://github.com/Dem13n/discussion-cards/discussions/8#discussion-3271937

**Comment by ayyilmaz** [comment]
Thank you very much for fixing composer window overflowing. 

But the new feature (setting card width) seems does not work. I have tried but nothing has changed.
